import {
  Mine,
  Subsidiary,
  ComplianceRequirement,
  Inspection,
  SafetyIncident,
  EnvironmentalReading,
  ProductionReport,
  Contractor,
  FieldReport,
  CorrectiveAction,
  AlertItem,
  NotificationItem,
  AIRiskAssessment,
  AnomalyItem,
  GrievanceItem,
  DocumentItem,
  AuditLogItem,
  UserProfile
} from '../src/types';

export const SEED_USERS: UserProfile[] = [
  {
    id: 'usr_admin_01',
    name: 'Dr. Rajeshwar Sharma',
    email: 'admin.gov@smartmine.gov.in',
    role: 'admin',
    roleTitle: 'Chief Technical Director & System Admin',
    department: 'Ministry of Coal / IT & Digital Governance Cell',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr_mine_01',
    name: 'Er. Arvind Mukhopadhyay',
    email: 'mine.official@smartmine.gov.in',
    role: 'mine_official',
    roleTitle: 'General Manager (Mining & Operations)',
    department: 'Bharat Coal Mine Alpha / BCCL Area IX',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr_insp_01',
    name: 'Smt. Priya Sundaram',
    email: 'inspector.dgms@smartmine.gov.in',
    role: 'inspector',
    roleTitle: 'Senior Dy. Director of Mines Safety',
    department: 'Directorate General of Mines Safety (DGMS), Eastern Zone',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr_corp_01',
    name: 'Shri Vikramaditya Das',
    email: 'corporate.exec@smartmine.gov.in',
    role: 'corporate',
    roleTitle: 'Executive Director (Safety & Production Monitoring)',
    department: 'Coal India Limited Corporate HQ, Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr_reg_01',
    name: 'Dr. Anurag Sengupta',
    email: 'regulatory.cpcb@smartmine.gov.in',
    role: 'regulatory',
    roleTitle: 'Zonal Joint Secretary / Compliance Auditor',
    department: 'Central Pollution Control Board & CCO Regional Directorate',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr_cont_01',
    name: 'K. S. Narayanan',
    email: 'contractor.rep@smartmine.gov.in',
    role: 'contractor',
    roleTitle: 'Lead Contractor Project Engineer',
    department: 'Apex Earthmovers & Heavy Haulage Pvt. Ltd.',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80'
  }
];

export const SEED_SUBSIDIARIES: Subsidiary[] = [
  {
    id: 'sub_bccl',
    name: 'Bharat Coking Coal Limited (BCCL)',
    code: 'BCCL',
    state: 'Jharkhand',
    headquarters: 'Koyla Bhawan, Dhanbad',
    totalMines: 36,
    complianceAvg: 74.2
  },
  {
    id: 'sub_ecl',
    name: 'Eastern Coalfields Limited (ECL)',
    code: 'ECL',
    state: 'West Bengal / Jharkhand',
    headquarters: 'Sanctoria, Asansol',
    totalMines: 42,
    complianceAvg: 68.9
  },
  {
    id: 'sub_secl',
    name: 'South Eastern Coalfields Limited (SECL)',
    code: 'SECL',
    state: 'Chhattisgarh',
    headquarters: 'Seepat Road, Bilaspur',
    totalMines: 58,
    complianceAvg: 88.5
  },
  {
    id: 'sub_ncl',
    name: 'Northern Coalfields Limited (NCL)',
    code: 'NCL',
    state: 'Madhya Pradesh / Uttar Pradesh',
    headquarters: 'Singrauli',
    totalMines: 10,
    complianceAvg: 94.1
  },
  {
    id: 'sub_mcl',
    name: 'Mahanadi Coalfields Limited (MCL)',
    code: 'MCL',
    state: 'Odisha',
    headquarters: 'Jagriti Vihar, Sambalpur',
    totalMines: 22,
    complianceAvg: 76.4
  },
  {
    id: 'sub_wcl',
    name: 'Western Coalfields Limited (WCL)',
    code: 'WCL',
    state: 'Maharashtra',
    headquarters: 'Coal Estate, Nagpur',
    totalMines: 28,
    complianceAvg: 81.3
  }
];

export const SEED_MINES: Mine[] = [
  {
    id: 'mine_alpha',
    code: 'BCCL-JHR-001',
    name: 'Bharat Coal Mine Alpha',
    subsidiaryId: 'sub_bccl',
    subsidiaryName: 'Bharat Coking Coal Limited (BCCL)',
    state: 'Jharkhand',
    district: 'Dhanbad',
    type: 'Underground',
    coordinates: { lat: 23.7957, lng: 86.4304 },
    riskLevel: 'High',
    riskScore: 78,
    complianceRate: 71.4,
    activeViolations: 4,
    openCorrectiveActions: 3,
    monthlyProductionTarget: 180000,
    monthlyProductionActual: 151200,
    managerName: 'Er. Arvind Mukhopadhyay',
    contactPhone: '+91-326-2234012',
    status: 'Notice Issued',
    lastInspectionDate: '2026-09-02',
    environmentalIndex: 68,
    safetyIncidentCount: 5
  },
  {
    id: 'mine_eastern',
    code: 'ECL-RNJ-014',
    name: 'Eastern Valley Open Cast',
    subsidiaryId: 'sub_ecl',
    subsidiaryName: 'Eastern Coalfields Limited (ECL)',
    state: 'West Bengal',
    district: 'Paschim Bardhaman',
    type: 'Open Cast',
    coordinates: { lat: 23.6889, lng: 86.9661 },
    riskLevel: 'Critical',
    riskScore: 89,
    complianceRate: 58.2,
    activeViolations: 6,
    openCorrectiveActions: 5,
    monthlyProductionTarget: 420000,
    monthlyProductionActual: 336000,
    managerName: 'Shri B. K. Chattopadhyay',
    contactPhone: '+91-341-2521908',
    status: 'Inspection Underway',
    lastInspectionDate: '2026-09-08',
    environmentalIndex: 52,
    safetyIncidentCount: 8
  },
  {
    id: 'mine_central',
    code: 'SECL-KRB-022',
    name: 'Central Ridge Mechanized Mine',
    subsidiaryId: 'sub_secl',
    subsidiaryName: 'South Eastern Coalfields Limited (SECL)',
    state: 'Chhattisgarh',
    district: 'Korba',
    type: 'Open Cast',
    coordinates: { lat: 22.3595, lng: 82.7501 },
    riskLevel: 'Medium',
    riskScore: 44,
    complianceRate: 85.0,
    activeViolations: 2,
    openCorrectiveActions: 2,
    monthlyProductionTarget: 750000,
    monthlyProductionActual: 762000,
    managerName: 'Er. Ramesh C. Verma',
    contactPhone: '+91-7759-241512',
    status: 'Operational',
    lastInspectionDate: '2026-08-28',
    environmentalIndex: 84,
    safetyIncidentCount: 2
  },
  {
    id: 'mine_north',
    code: 'NCL-SNG-009',
    name: 'Northern Energy Pit 4',
    subsidiaryId: 'sub_ncl',
    subsidiaryName: 'Northern Coalfields Limited (NCL)',
    state: 'Madhya Pradesh',
    district: 'Singrauli',
    type: 'Open Cast',
    coordinates: { lat: 24.1997, lng: 82.6644 },
    riskLevel: 'Low',
    riskScore: 16,
    complianceRate: 96.2,
    activeViolations: 0,
    openCorrectiveActions: 1,
    monthlyProductionTarget: 600000,
    monthlyProductionActual: 618500,
    managerName: 'Dr. Sudhir Pandey',
    contactPhone: '+91-7805-267819',
    status: 'Operational',
    lastInspectionDate: '2026-08-15',
    environmentalIndex: 92,
    safetyIncidentCount: 0
  },
  {
    id: 'mine_shakti',
    code: 'MCL-TLR-018',
    name: 'Shakti Open Cast Mine',
    subsidiaryId: 'sub_mcl',
    subsidiaryName: 'Mahanadi Coalfields Limited (MCL)',
    state: 'Odisha',
    district: 'Angul',
    type: 'Open Cast',
    coordinates: { lat: 20.9509, lng: 85.2166 },
    riskLevel: 'High',
    riskScore: 73,
    complianceRate: 74.0,
    activeViolations: 3,
    openCorrectiveActions: 3,
    monthlyProductionTarget: 520000,
    monthlyProductionActual: 468000,
    managerName: 'Shri Debabrata Nayak',
    contactPhone: '+91-6760-234710',
    status: 'Production Advisory',
    lastInspectionDate: '2026-09-04',
    environmentalIndex: 64,
    safetyIncidentCount: 4
  },
  {
    id: 'mine_surya',
    code: 'WCL-NGP-033',
    name: 'Surya Deep Underground Mine',
    subsidiaryId: 'sub_wcl',
    subsidiaryName: 'Western Coalfields Limited (WCL)',
    state: 'Maharashtra',
    district: 'Nagpur',
    type: 'Underground',
    coordinates: { lat: 21.1458, lng: 79.0882 },
    riskLevel: 'Medium',
    riskScore: 52,
    complianceRate: 81.8,
    activeViolations: 2,
    openCorrectiveActions: 1,
    monthlyProductionTarget: 140000,
    monthlyProductionActual: 135800,
    managerName: 'Er. Manoj Deshmukh',
    contactPhone: '+91-712-2589021',
    status: 'Operational',
    lastInspectionDate: '2026-08-20',
    environmentalIndex: 79,
    safetyIncidentCount: 2
  }
];

export const SEED_COMPLIANCE_REQUIREMENTS: ComplianceRequirement[] = [
  {
    id: 'comp_001',
    code: 'DGMS-CMR-2017-R153',
    title: 'Tele-monitoring of Carbon Monoxide & Methane (CMR Reg 153)',
    description: 'Continuous tele-monitoring and automatic recording of CH4, CO, and air velocity in Degree III gassy seams with telemetry links.',
    category: 'Safety',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    subsidiaryId: 'sub_bccl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Continuous',
    dueDate: '2026-09-05',
    status: 'Overdue',
    risk: 'Critical',
    responsiblePerson: 'Er. Arvind Mukhopadhyay',
    responsibleDept: 'Safety & Ventilation Directorate',
    requiredDocuments: ['Sensor Calibration Certificate', 'DGMS Form IV-B Telemetry Log'],
    notes: ['Telemetry gateway sensor in District 3 seam experienced serial sync loss on Aug 30.'],
    lastUpdated: '2026-09-06',
    escalationLevel: 2
  },
  {
    id: 'comp_002',
    code: 'DGMS-CIR-2022-SLP04',
    title: 'Slope Stability Radar (SSR) Geo-Monitoring (Reg 106)',
    description: 'Quarterly third-party geotechnical slope stability audit and real-time prism displacement monitoring on benches > 30m.',
    category: 'Safety',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    subsidiaryId: 'sub_ecl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Quarterly',
    dueDate: '2026-08-30',
    status: 'Overdue',
    risk: 'Critical',
    responsiblePerson: 'Shri B. K. Chattopadhyay',
    responsibleDept: 'Civil & Geotechnical Survey',
    requiredDocuments: ['SSR Vector Displacement Map', 'CIMFR Geotechnical Clearance'],
    notes: ['North-western overburden dump slope benchmark displacement exceeded 14mm threshold.'],
    lastUpdated: '2026-09-01',
    escalationLevel: 2
  },
  {
    id: 'comp_003',
    code: 'CPCB-EIA-WATER-2024',
    title: 'Effluent Treatment Plant Discharge TSS & Heavy Metals (CPCB S.O. 3305)',
    description: 'Fortnightly water discharge analysis ensuring TSS < 100 mg/l, pH 6.5-8.5, and iron < 3 mg/l prior to discharge into natural drainage.',
    category: 'Environmental',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    subsidiaryId: 'sub_ecl',
    regulatoryAuthority: 'CPCB / SPCB',
    frequency: 'Monthly',
    dueDate: '2026-09-02',
    status: 'Non-Compliant',
    risk: 'High',
    responsiblePerson: 'Dr. Niloy Sen',
    responsibleDept: 'Environmental Management Division',
    requiredDocuments: ['NABL Accredited Lab Test Report', 'ETP Flowmeter Calibration'],
    notes: ['TSS recorded at 168 mg/l on Outfall A after heavy monsoonal siltation.'],
    lastUpdated: '2026-09-05',
    escalationLevel: 1
  },
  {
    id: 'comp_004',
    code: 'DGMS-EXPL-2017-R165',
    title: 'Statutory Explosives Magazine Safety & Seismograph Logs',
    description: 'Submission of monthly ground vibration PPV seismograph logs and explosive consumption reconciliation under CMR Reg 165.',
    category: 'Explosives & Blasting',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    subsidiaryId: 'sub_mcl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Monthly',
    dueDate: '2026-09-15',
    status: 'At Risk',
    risk: 'High',
    responsiblePerson: 'Er. S. Routray',
    responsibleDept: 'Blasting & Explosives Operations',
    requiredDocuments: ['PESO License Form LE-3', 'Peak Particle Velocity (PPV) Log'],
    notes: ['3 residential periphery complaints logged regarding blast air-overpressure > 120 dB.'],
    lastUpdated: '2026-09-10'
  },
  {
    id: 'comp_005',
    code: 'LAB-CONTR-ACT-1970',
    title: 'Contract Labour (R&A) Act 1970 & EPFO / ESIC Form XXIV Compliance',
    description: 'Mandatory verification of wages, PF remittance challans, and statutory Form XXIV for all outsourced heavy haulage contractors.',
    category: 'Labour Regulations',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    subsidiaryId: 'sub_bccl',
    regulatoryAuthority: 'Ministry of Labour',
    frequency: 'Monthly',
    dueDate: '2026-09-18',
    status: 'In Progress',
    risk: 'Medium',
    responsiblePerson: 'Smt. Anjali Soren',
    responsibleDept: 'Personnel & Industrial Relations',
    requiredDocuments: ['EPF Electronic Challan Receipt', 'ESIC Contribution Statement'],
    notes: ['Verification for 320 outsourced tipper operators ongoing.'],
    lastUpdated: '2026-09-11'
  },
  {
    id: 'comp_006',
    code: 'MOEF-EC-COND-08',
    title: 'Half-Yearly Environmental Clearance (EC) Compliance Report',
    description: 'Comprehensive 6-monthly report on green belt development, ambient air PM10 suppression, and groundwater piezometer telemetry.',
    category: 'Environmental',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    subsidiaryId: 'sub_secl',
    regulatoryAuthority: 'MoEFCC',
    frequency: 'Bi-Annual',
    dueDate: '2026-10-30',
    status: 'Compliant',
    risk: 'Low',
    responsiblePerson: 'Er. Ramesh C. Verma',
    responsibleDept: 'Environment & Forestry',
    requiredDocuments: ['Six-Monthly Compliance Booklet', 'Satellite Green Canopy Map'],
    notes: ['Submitted via MoEFCC Parivesh portal. Acknowledgment receipt ref #PRV-88219.'],
    lastUpdated: '2026-08-25'
  },
  {
    id: 'comp_007',
    code: 'DGMS-CMR-2017-R083',
    title: 'Statutory Mining Plan & Five-Year Progressive Mine Closure Plan',
    description: 'Annual certification of pit boundary demarcation, concurrent backfilling audit, and financial assurance escrow bank guarantee.',
    category: 'Production / Mining Plan',
    mineId: 'mine_north',
    mineName: 'Northern Energy Pit 4',
    subsidiaryId: 'sub_ncl',
    regulatoryAuthority: 'Coal Controller Org (CCO)',
    frequency: 'Annual',
    dueDate: '2026-11-15',
    status: 'Compliant',
    risk: 'Low',
    responsiblePerson: 'Dr. Sudhir Pandey',
    responsibleDept: 'Planning & Project Development',
    requiredDocuments: ['CCO Approved Mining Scheme', 'Escrow Account Bank Guarantee'],
    notes: ['Bank guarantee renewed with State Bank of India Singrauli branch.'],
    lastUpdated: '2026-08-10'
  },
  {
    id: 'comp_008',
    code: 'DGMS-CMR-2017-R130',
    title: 'Stone Dust Barrier & Coal Dust Explosion Suppression (CMR Reg 130)',
    description: 'Bi-weekly combustible dust analysis in return airways and certification of heavy type stone dust barriers in conveyor drifts.',
    category: 'Safety',
    mineId: 'mine_surya',
    mineName: 'Surya Deep Underground Mine',
    subsidiaryId: 'sub_wcl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Monthly',
    dueDate: '2026-09-22',
    status: 'Compliant',
    risk: 'Low',
    responsiblePerson: 'Er. Manoj Deshmukh',
    responsibleDept: 'Underground Safety Wing',
    requiredDocuments: ['Combustible Dust Lab Analysis Sheet', 'Barrier Inspection Certificate'],
    notes: ['Sample collected from Seam 4 intake drift met minimum 75% incombustible matter norm.'],
    lastUpdated: '2026-09-08'
  },
  {
    id: 'comp_009',
    code: 'SPCB-AIR-CTO-2025',
    title: 'Consent to Operate (CTO) Ambient Air Quality Mist Cannons Mandate',
    description: 'Installation and telemetry streaming of 14 high-pressure truck-mounted mist cannons along haul roads to suppress PM10 < 100 ug/m3.',
    category: 'Environmental',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    subsidiaryId: 'sub_mcl',
    regulatoryAuthority: 'CPCB / SPCB',
    frequency: 'Quarterly',
    dueDate: '2026-09-12',
    status: 'Overdue',
    risk: 'High',
    responsiblePerson: 'Shri Debabrata Nayak',
    responsibleDept: 'Civil & Environmental Works',
    requiredDocuments: ['SPCB Continuous Air Quality Stream Log', 'Equipment Commissioning Memo'],
    notes: ['2 mist cannons on primary haul loop B out of service due to pump failure.'],
    lastUpdated: '2026-09-12',
    escalationLevel: 1
  },
  {
    id: 'comp_010',
    code: 'DGMS-CMR-2017-R104',
    title: 'Dump Height & Berm Dimensions Verification (CMR Reg 104)',
    description: 'Quarterly drone-based photogrammetric volumetric survey of overburden dumps ensuring overall slope < 28 degrees and terrace width > 30m.',
    category: 'Safety',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    subsidiaryId: 'sub_ecl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Quarterly',
    dueDate: '2026-09-25',
    status: 'At Risk',
    risk: 'Critical',
    responsiblePerson: 'Shri B. K. Chattopadhyay',
    responsibleDept: 'Mine Survey & Drone Wing',
    requiredDocuments: ['Orthomosaic DTM Model', 'Certified Mine Surveyor Certificate'],
    notes: ['Drone flight completed on Sept 7; contour processing shows localized bench narrowing to 21m.'],
    lastUpdated: '2026-09-09'
  },
  {
    id: 'comp_011',
    code: 'MINES-RULE-1955-R29',
    title: 'Initial & Periodic Medical Examination (PME) for Underground Miners',
    description: 'Annual chest radiograph (ILO standard) and spirometry lung capacity screening for silicosis and pneumoconiosis under Mines Rule 29B.',
    category: 'Labour Regulations',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    subsidiaryId: 'sub_bccl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Annual',
    dueDate: '2026-10-10',
    status: 'In Progress',
    risk: 'Medium',
    responsiblePerson: 'Dr. C. P. Mahato (CMO)',
    responsibleDept: 'Occupational Health Centre',
    requiredDocuments: ['Form O Medical Record Registers', 'ILO X-Ray Radiologist Summary'],
    notes: ['Batch 4 (140 underground timberers and haulage crew) scheduled for Sept 18-20.'],
    lastUpdated: '2026-09-04'
  },
  {
    id: 'comp_012',
    code: 'DGMS-TECH-2023-FRL02',
    title: 'Flame-Proof (FLP) & Intrinsically Safe (IS) Electrical Certification',
    description: 'Mandatory annual insulation resistance, earth continuity, and FLP enclosure seal inspection for all 3.3kV substations in gassy seam.',
    category: 'Safety',
    mineId: 'mine_surya',
    mineName: 'Surya Deep Underground Mine',
    subsidiaryId: 'sub_wcl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Annual',
    dueDate: '2026-10-05',
    status: 'Compliant',
    risk: 'Low',
    responsiblePerson: 'Er. Manoj Deshmukh',
    responsibleDept: 'Electrical & Mechanical Engineering',
    requiredDocuments: ['CIMFR FLP Retest Certificate', 'Statutory Electrical Supervisor Register'],
    notes: ['Substation #2 overhaul completed with zero earth fault leakage.'],
    lastUpdated: '2026-08-30'
  },
  {
    id: 'comp_013',
    code: 'DGMS-CMR-2017-R170',
    title: 'Controlled Blasting & Pre-Split Vibration Compliance near Periphery',
    description: 'DGMS permission conditions requiring electronic detonators and signature hole analysis for blasting within 300m of railway siding.',
    category: 'Explosives & Blasting',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    subsidiaryId: 'sub_secl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Quarterly',
    dueDate: '2026-09-30',
    status: 'Compliant',
    risk: 'Low',
    responsiblePerson: 'Er. Ramesh C. Verma',
    responsibleDept: 'Blasting Engineering Division',
    requiredDocuments: ['Electronic Detonator Timing Map', 'Railway Authority Joint Clearance'],
    notes: ['All 12 production rounds this quarter maintained PPV < 5.0 mm/sec.'],
    lastUpdated: '2026-09-02'
  },
  {
    id: 'comp_014',
    code: 'CPCB-FLYASH-2021',
    title: 'Fly Ash Disposal in Abandoned Mine Void Backfilling Norms',
    description: 'Strict adherence to CPCB guidelines for ash stowing, monitoring leachability of heavy metals in downstream monitoring wells.',
    category: 'Environmental',
    mineId: 'mine_north',
    mineName: 'Northern Energy Pit 4',
    subsidiaryId: 'sub_ncl',
    regulatoryAuthority: 'CPCB / SPCB',
    frequency: 'Quarterly',
    dueDate: '2026-10-15',
    status: 'Compliant',
    risk: 'Low',
    responsiblePerson: 'Dr. Sudhir Pandey',
    responsibleDept: 'Civil & Environment',
    requiredDocuments: ['Groundwater Leachate Analysis', 'NTPC Ash Supply Reconciliation'],
    notes: ['Void 2B backfilled with 42,000 MT fly ash; groundwater cadmium & lead below detection limits.'],
    lastUpdated: '2026-08-20'
  },
  {
    id: 'comp_015',
    code: 'DGMS-CMR-2017-R148',
    title: 'Auxiliary Ventilation & Methane Drainage in Heading Advances',
    description: 'CMR Reg 148 compliance requiring minimum 30 m3/min air delivery at face and automated power interlock on ventilation trip.',
    category: 'Safety',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    subsidiaryId: 'sub_bccl',
    regulatoryAuthority: 'DGMS',
    frequency: 'Monthly',
    dueDate: '2026-09-10',
    status: 'Non-Compliant',
    risk: 'High',
    responsiblePerson: 'Er. Arvind Mukhopadhyay',
    responsibleDept: 'Ventilation Officer',
    requiredDocuments: ['Air Measurement Book (Form IV)', 'Fan Interlock Calibration Sheet'],
    notes: ['Face ducting leakage identified in Level 7 West heading during DGMS surprise spot audit.'],
    lastUpdated: '2026-09-10',
    escalationLevel: 1
  }
];

export const SEED_INSPECTIONS: Inspection[] = [
  {
    id: 'insp_001',
    code: 'INSP-2026-0902-DGMS',
    title: 'Statutory Safety Audit & Methane Telemetry Verification',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    inspectorName: 'Smt. Priya Sundaram',
    inspectorRole: 'Senior Dy. Director of Mines Safety (DGMS)',
    type: 'Statutory DGMS',
    scheduledDate: '2026-09-02',
    date: '2026-09-02',
    status: 'Requires Action',
    riskLevel: 'High',
    locationDetails: 'Seam XV, Heading 7 West, District 3 Incline',
    coordinates: { lat: 23.7962, lng: 86.4312 },
    findingsCount: 4,
    violationsCount: 2,
    observations: [
      'Observed methane sensor calibration record missing for 2 weeks on telemetry rack.',
      'Flexible ventilation ducting torn at 42m marker causing 28% air volume loss at working face.',
      'Emergency refuge chamber oxygen cylinders checked and found at full statutory pressure.'
    ],
    findings: [
      {
        id: 'fnd_001',
        category: 'Ventilation & Gas',
        severity: 'Critical',
        clause: 'CMR 2017 Reg 153(2)',
        description: 'Automatic interlock between main exhaust fan trip and coal cutting shearer power supply found disabled by temporary bypass jumper.',
        immediateActionTaken: 'Jumper removed immediately in presence of inspector; power supply isolated.',
        hasViolation: true,
        correctiveActionId: 'ca_001'
      },
      {
        id: 'fnd_002',
        category: 'Occupational Safety',
        severity: 'Moderate',
        clause: 'CMR 2017 Reg 184',
        description: 'Two haulage roadway roller assemblies seized, showing friction wear and coal dust accumulation.',
        immediateActionTaken: 'Roadway clear order issued to safety officer.',
        hasViolation: true,
        correctiveActionId: 'ca_002'
      }
    ]
  },
  {
    id: 'insp_002',
    code: 'INSP-2026-0908-SLOPE',
    title: 'Surprise Geotechnical Slope Stability Inspection',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    inspectorName: 'Er. Rajesh K. Mohanty',
    inspectorRole: 'Joint Director of Mines Safety (Open Cast)',
    type: 'Special Surprise Inspection',
    scheduledDate: '2026-09-08',
    date: '2026-09-08',
    status: 'Requires Action',
    riskLevel: 'Critical',
    locationDetails: 'Overburden Bench OB-4 (North-Western Flank)',
    coordinates: { lat: 23.6895, lng: 86.9675 },
    findingsCount: 5,
    violationsCount: 3,
    observations: [
      'Tension cracks observed along crest of bench OB-4 ranging from 3cm to 8cm width over 45 meters.',
      'Haul road ramp angle exceeds 1 in 16 permissible gradient on switchback #3.',
      'Dust suppression bowsers operational but water spray coverage uneven.'
    ],
    findings: [
      {
        id: 'fnd_003',
        category: 'Geotechnical & Slope Safety',
        severity: 'Critical',
        clause: 'CMR 2017 Reg 106(1)',
        description: 'Failure to de-stress crest of bench OB-4 following tension crack identification; heavy dumper movement continued under unstable toe.',
        immediateActionTaken: 'Section 22(3) prohibitive notice issued to stop heavy vehicular access on Ramp 3.',
        hasViolation: true,
        correctiveActionId: 'ca_003'
      },
      {
        id: 'fnd_004',
        category: 'Plant & Machinery',
        severity: 'Major',
        clause: 'DGMS Tech Circular 06/2020',
        description: 'Three 100-tonne haul trucks operated by contractor lacking rear-view cameras and proximity detection sensors.',
        immediateActionTaken: 'Dumpers grounded in central workshop till retrofit verification.',
        hasViolation: true,
        correctiveActionId: 'ca_004'
      }
    ]
  },
  {
    id: 'insp_003',
    code: 'INSP-2026-0828-ENV',
    title: 'Comprehensive Environmental & Effluent Monitoring Audit',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    inspectorName: 'Dr. Anurag Sengupta',
    inspectorRole: 'Zonal Joint Secretary (SPCB / CPCB)',
    type: 'Environmental Audit',
    scheduledDate: '2026-08-28',
    date: '2026-08-28',
    status: 'Completed',
    riskLevel: 'Medium',
    locationDetails: 'ETP Discharge Channel & Central Haul Corridor',
    coordinates: { lat: 22.3610, lng: 82.7525 },
    findingsCount: 2,
    violationsCount: 0,
    observations: [
      'ETP operating within statutory limits (TSS: 42 mg/l, pH: 7.2).',
      'Green belt along mine boundary well maintained with 82% sapling survival rate.',
      'Minor fugitive dust observed near coal handling conveyor transfer chute #2.'
    ],
    findings: [
      {
        id: 'fnd_005',
        category: 'Dust Control',
        severity: 'Minor',
        clause: 'SPCB CTO Condition #14',
        description: 'Conveyor chute #2 skirting rubber worn, leading to localized coal dust spillage.',
        immediateActionTaken: 'Maintenance crew assigned to replace skirting before evening shift.',
        hasViolation: false
      }
    ]
  },
  {
    id: 'insp_004',
    code: 'INSP-2026-0815-ISO',
    title: 'Integrated Safety Management & Statutory Labour Review',
    mineId: 'mine_north',
    mineName: 'Northern Energy Pit 4',
    inspectorName: 'Smt. Priya Sundaram',
    inspectorRole: 'Senior Dy. Director of Mines Safety',
    type: 'Routine Safety',
    scheduledDate: '2026-08-15',
    date: '2026-08-15',
    status: 'Closed',
    riskLevel: 'Low',
    locationDetails: 'Entire Operational Leasehold Area',
    coordinates: { lat: 24.2010, lng: 82.6660 },
    findingsCount: 1,
    violationsCount: 0,
    observations: [
      'Excellent bench dressing, berm heights compliant with 1.5x tyre diameter mandate.',
      'PME registers up to date with 100% compliance for active workforce.',
      'Safety committee meetings conducted monthly with recorded minutes.'
    ],
    findings: []
  },
  {
    id: 'insp_005',
    code: 'INSP-2026-0904-EXP',
    title: 'Explosives Magazine & Deep Hole Blasting Safety Review',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    inspectorName: 'Er. Rajesh K. Mohanty',
    inspectorRole: 'Joint Director of Mines Safety',
    type: 'Statutory DGMS',
    scheduledDate: '2026-09-04',
    date: '2026-09-04',
    status: 'Requires Action',
    riskLevel: 'High',
    locationDetails: 'Magazines A & B, Pit 2 Face Blasting Zone',
    coordinates: { lat: 20.9520, lng: 85.2180 },
    findingsCount: 3,
    violationsCount: 1,
    observations: [
      'Magazine security guard post equipped with CCTV coverage and perimeter fencing intact.',
      'Vibration monitoring seismographs calibrated up to June 2026.',
      'Perimeter blasting warning siren audible up to 1.8km radius.'
    ],
    findings: [
      {
        id: 'fnd_006',
        category: 'Explosives Storage',
        severity: 'Major',
        clause: 'CMR 2017 Reg 168',
        description: 'Electric blasting cap inventory ledger showed discrepancy of 12 delay units between physical bin count and statutory daily issue register.',
        immediateActionTaken: 'Ledger frozen and joint reconciliation conducted under Blasting Officer supervision.',
        hasViolation: true,
        correctiveActionId: 'ca_005'
      }
    ]
  }
];

export const SEED_CORRECTIVE_ACTIONS: CorrectiveAction[] = [
  {
    id: 'ca_001',
    code: 'CAPA-2026-001',
    title: 'Restore Automated Shearer Power Interlock & Recalibrate Telemetry',
    source: 'Inspection',
    sourceId: 'insp_001',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    violationCategory: 'Ventilation & Gas Safety',
    description: 'Permanently remove bypass wiring, rewire fail-safe interlock relay to main substation trip breaker, and submit DGMS compliance affidavit.',
    responsiblePerson: 'Er. Arvind Mukhopadhyay',
    responsibleDept: 'Electrical & Instrumentation Wing',
    priority: 'Critical',
    dueDate: '2026-09-07',
    status: 'Overdue',
    escalationLevel: 2,
    createdAt: '2026-09-02',
    resolutionNotes: 'Interlock rewired on Sept 4, pending final DGMS joint verification inspection.'
  },
  {
    id: 'ca_002',
    code: 'CAPA-2026-002',
    title: 'Replace Seized Haulage Road Rollers & Stone Dust Application',
    source: 'Inspection',
    sourceId: 'insp_001',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    violationCategory: 'Occupational Safety',
    description: 'Replace 8 seized steel rollers with grease-sealed polyurethane rollers along District 3 incline and clean accumulated coal dust.',
    responsiblePerson: 'Shri S. K. Murmu',
    responsibleDept: 'Underground Mechanical',
    priority: 'Medium',
    dueDate: '2026-09-14',
    status: 'In Progress',
    createdAt: '2026-09-02'
  },
  {
    id: 'ca_003',
    code: 'CAPA-2026-003',
    title: 'Execute Dozer Benching to De-Stress Overburden Bench OB-4',
    source: 'Inspection',
    sourceId: 'insp_002',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    violationCategory: 'Slope Stability',
    description: 'Mobilize 2 D-375 crawler dozers to push back unstable 45-meter crest, reduce slope angle to 26 degrees, and re-establish safety berm.',
    responsiblePerson: 'Shri B. K. Chattopadhyay',
    responsibleDept: 'Mining & Heavy Earthmoving',
    priority: 'Critical',
    dueDate: '2026-09-11',
    status: 'Escalated',
    escalationLevel: 3,
    createdAt: '2026-09-08',
    resolutionNotes: 'Escalated to Director Technical (ECL) due to production suspension on Ramp 3.'
  },
  {
    id: 'ca_004',
    code: 'CAPA-2026-004',
    title: 'Fit Contractor Dumpers with DGMS Mandated Proximity Radar & Cameras',
    source: 'Inspection',
    sourceId: 'insp_002',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    violationCategory: 'Plant & Machinery Safety',
    description: 'Ensure Apex Earthmovers completes installation of rear-view ultrasonic obstacle sensors and fatigue alert cameras on all 14 dumpers.',
    responsiblePerson: 'K. S. Narayanan',
    responsibleDept: 'Apex Earthmovers Pvt Ltd',
    priority: 'High',
    dueDate: '2026-09-16',
    status: 'In Progress',
    createdAt: '2026-09-08'
  },
  {
    id: 'ca_005',
    code: 'CAPA-2026-005',
    title: 'Electronic Explosives Inventory Barcode System Reconciliation',
    source: 'Inspection',
    sourceId: 'insp_005',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    violationCategory: 'Explosives Storage',
    description: 'Install handheld 2D barcode scanner at Magazine A dispatch counter and perform 100% stock reconciliation with PESO portal.',
    responsiblePerson: 'Er. S. Routray',
    responsibleDept: 'Blasting Operations',
    priority: 'High',
    dueDate: '2026-09-12',
    status: 'Resolved',
    createdAt: '2026-09-04',
    resolvedAt: '2026-09-11',
    resolutionNotes: 'Reconciliation completed. Barcode system operational with PESO daily sync.'
  },
  {
    id: 'ca_006',
    code: 'CAPA-2026-006',
    title: 'Commission Dedicated Settling Pond for ETP Outfall A',
    source: 'Environmental Exceedance',
    sourceId: 'comp_003',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    violationCategory: 'Environmental Effluent',
    description: 'Excavate 5000 m3 secondary retention sump with chemical flocculation dosing to arrest monsoon runoff TSS below 100 mg/l.',
    responsiblePerson: 'Dr. Niloy Sen',
    responsibleDept: 'Civil & Environment',
    priority: 'High',
    dueDate: '2026-09-20',
    status: 'In Progress',
    createdAt: '2026-09-05'
  },
  {
    id: 'ca_007',
    code: 'CAPA-2026-007',
    title: 'Repair High-Pressure Haul Road Mist Cannons 3 & 4',
    source: 'Environmental Exceedance',
    sourceId: 'comp_009',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    violationCategory: 'Fugitive Dust Suppression',
    description: 'Procure replacement booster pumps and restore automated mist fogger operation along primary dispatch siding.',
    responsiblePerson: 'Shri Debabrata Nayak',
    responsibleDept: 'Mechanical Services',
    priority: 'Medium',
    dueDate: '2026-09-15',
    status: 'Assigned',
    createdAt: '2026-09-10'
  },
  {
    id: 'ca_008',
    code: 'CAPA-2026-008',
    title: 'Mandatory Re-Induction on Continuous Gas Detector Usage',
    source: 'Safety Incident',
    sourceId: 'inc_002',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    violationCategory: 'PPE & Gas Monitoring',
    description: 'Conduct mandatory 4-hour refresher training for all 180 underground timbermen and machine operators on toxic gas badges.',
    responsiblePerson: 'Dr. C. P. Mahato',
    responsibleDept: 'Vocational Training Centre (VTC)',
    priority: 'High',
    dueDate: '2026-09-18',
    status: 'In Progress',
    createdAt: '2026-09-09'
  }
];

export const SEED_SAFETY_INCIDENTS: SafetyIncident[] = [
  {
    id: 'inc_001',
    code: 'INC-2026-0909-01',
    type: 'Slope Stability Warning',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    location: 'Overburden Dump OB-4, North Face',
    reportedBy: 'Field Inspector S. K. Ghosh',
    reportedDate: '2026-09-09 07:45',
    severity: 'Critical',
    peopleInvolved: 0,
    description: 'Geotechnical monitoring detected 18mm cumulative displacement over 24 hours along crest line. Small boulder roll observed at 07:30.',
    immediateAction: 'Haul road switchback closed to all traffic; equipment withdrawn beyond 60-meter exclusion boundary.',
    status: 'Action Assigned',
    coordinates: { lat: 23.6898, lng: 86.9678 },
    calculatedRisk: 'Critical'
  },
  {
    id: 'inc_002',
    code: 'INC-2026-0907-02',
    type: 'PPE Violation',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    location: 'District 3 Incline Drift',
    reportedBy: 'Safety Supervisor P. Soren',
    reportedDate: '2026-09-07 14:15',
    severity: 'Moderate',
    peopleInvolved: 3,
    description: 'Three contractor timberers found working near return airway without multi-gas personal monitors and dust masks.',
    immediateAction: 'Workers pulled back to intake fresh air base; penalty issued to contractor Apex Haulage.',
    status: 'Investigating',
    coordinates: { lat: 23.7959, lng: 86.4308 },
    calculatedRisk: 'High'
  },
  {
    id: 'inc_003',
    code: 'INC-2026-0903-03',
    type: 'Near Miss',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    location: 'Coal Handling Plant Bunker 4',
    reportedBy: 'Operator M. K. Baghel',
    reportedDate: '2026-09-03 11:20',
    severity: 'Minor',
    peopleInvolved: 1,
    description: 'Empty haul truck reversed into bumper block while spotter was in blind spot. Proximity sensor alert prevented collision.',
    immediateAction: 'Driver counselled; spotter high-visibility LED baton provided.',
    status: 'Resolved',
    coordinates: { lat: 22.3600, lng: 82.7510 },
    calculatedRisk: 'Low'
  },
  {
    id: 'inc_004',
    code: 'INC-2026-0831-04',
    type: 'Gas Influx / Ventilation',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    location: 'Seam XV Blind Heading',
    reportedBy: 'Overman T. K. Roy',
    reportedDate: '2026-08-31 03:30',
    severity: 'Major',
    peopleInvolved: 6,
    description: 'Methane level briefly spiked to 1.15% following blasting round due to delayed auxiliary fan restart.',
    immediateAction: 'Face evacuated immediately; ventilation resumed until CH4 dropped below 0.35% before re-entry.',
    status: 'Resolved',
    coordinates: { lat: 23.7965, lng: 86.4315 },
    calculatedRisk: 'High'
  },
  {
    id: 'inc_005',
    code: 'INC-2026-0826-05',
    type: 'Equipment Incident',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    location: 'Pit 1 In-pit Crusher Ramp',
    reportedBy: 'Shift Eng. B. Pradhan',
    reportedDate: '2026-08-26 19:40',
    severity: 'Moderate',
    peopleInvolved: 2,
    description: 'Hydraulic hose rupture on 12 m3 electric rope shovel caused localized hydraulic fluid spill on haul track.',
    immediateAction: 'Spill containment absorbent applied; shovel isolated and hydraulic line replaced.',
    status: 'Resolved',
    coordinates: { lat: 20.9515, lng: 85.2172 },
    calculatedRisk: 'Medium'
  }
];

export const SEED_ENVIRONMENTAL_READINGS: EnvironmentalReading[] = [
  {
    id: 'env_001',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    date: '2026-09-12',
    parameter: 'PM10',
    value: 142.5,
    unit: 'µg/m³',
    threshold: 100.0,
    status: 'Exceeded',
    location: 'North Perimeter Boundary / Residential Buffer'
  },
  {
    id: 'env_002',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    date: '2026-09-12',
    parameter: 'PM2.5',
    value: 78.2,
    unit: 'µg/m³',
    threshold: 60.0,
    status: 'Exceeded',
    location: 'North Perimeter Boundary'
  },
  {
    id: 'env_003',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    date: '2026-09-12',
    parameter: 'Effluent TSS',
    value: 168.0,
    unit: 'mg/l',
    threshold: 100.0,
    status: 'Exceeded',
    location: 'ETP Outfall Channel A'
  },
  {
    id: 'env_004',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    date: '2026-09-12',
    parameter: 'Water pH',
    value: 7.4,
    unit: 'pH',
    threshold: 8.5,
    status: 'Normal',
    location: 'Mine Sump Discharge Point'
  },
  {
    id: 'env_005',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    date: '2026-09-12',
    parameter: 'Noise Level',
    value: 78.4,
    unit: 'dB(A)',
    threshold: 75.0,
    status: 'Advisory',
    location: 'Main Exhaust Ventilation Fan Shaft #1'
  },
  {
    id: 'env_006',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    date: '2026-09-12',
    parameter: 'PM10',
    value: 88.0,
    unit: 'µg/m³',
    threshold: 100.0,
    status: 'Normal',
    location: 'Pithead Railway Siding Area'
  },
  {
    id: 'env_007',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    date: '2026-09-12',
    parameter: 'PM10',
    value: 124.0,
    unit: 'µg/m³',
    threshold: 100.0,
    status: 'Exceeded',
    location: 'Haul Road Loop B (Near Siding 2)'
  },
  {
    id: 'env_008',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    date: '2026-09-12',
    parameter: 'PM10',
    value: 68.5,
    unit: 'µg/m³',
    threshold: 100.0,
    status: 'Normal',
    location: 'Township Boundary Ambient Station'
  },
  {
    id: 'env_009',
    mineId: 'mine_north',
    mineName: 'Northern Energy Pit 4',
    date: '2026-09-12',
    parameter: 'PM10',
    value: 52.0,
    unit: 'µg/m³',
    threshold: 100.0,
    status: 'Normal',
    location: 'Continuous CAAQMS Station 1'
  },
  {
    id: 'env_010',
    mineId: 'mine_north',
    mineName: 'Northern Energy Pit 4',
    date: '2026-09-12',
    parameter: 'Water pH',
    value: 7.1,
    unit: 'pH',
    threshold: 8.5,
    status: 'Normal',
    location: 'Ash Stowing Drainage Monitor Well 3'
  }
];

export const SEED_PRODUCTION_REPORTS: ProductionReport[] = [
  {
    id: 'prod_001',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    date: '2026-09-11',
    targetTonnage: 6000,
    actualTonnage: 4720,
    variance: -21.3,
    equipmentAvailabilityPercent: 71.5,
    operationalNotes: 'Section 22 notice and ventilation duct repairs reduced coal cutting hours by 4.5 hours in Shift B.',
    anomalyDetected: true,
    anomalyReason: 'Sudden 21% production drop correlated with statutory ventilation repairs.'
  },
  {
    id: 'prod_002',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    date: '2026-09-11',
    targetTonnage: 14000,
    actualTonnage: 9800,
    variance: -30.0,
    equipmentAvailabilityPercent: 62.0,
    operationalNotes: 'Ramp 3 traffic suspension due to slope tension cracks halted 24 tipper rotations.',
    anomalyDetected: true,
    anomalyReason: 'Major 30% shortfall caused by slope hazard traffic halt on principal haul route.'
  },
  {
    id: 'prod_003',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    date: '2026-09-11',
    targetTonnage: 25000,
    actualTonnage: 25900,
    variance: 3.6,
    equipmentAvailabilityPercent: 91.2,
    operationalNotes: 'Smooth operations across all 3 production shifts; in-pit crushing operating at nominal capacity.',
    anomalyDetected: false
  },
  {
    id: 'prod_004',
    mineId: 'mine_north',
    mineName: 'Northern Energy Pit 4',
    date: '2026-09-11',
    targetTonnage: 20000,
    actualTonnage: 20850,
    variance: 4.25,
    equipmentAvailabilityPercent: 94.0,
    operationalNotes: 'Dragline #2 completed scheduled bench pass ahead of target.',
    anomalyDetected: false
  },
  {
    id: 'prod_005',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    date: '2026-09-11',
    targetTonnage: 17500,
    actualTonnage: 15400,
    variance: -12.0,
    equipmentAvailabilityPercent: 79.5,
    operationalNotes: 'Blasting reconciliation audit delayed morning shot by 2 hours.',
    anomalyDetected: true,
    anomalyReason: 'Production lag due to blasting clearance delay.'
  },
  {
    id: 'prod_006',
    mineId: 'mine_surya',
    mineName: 'Surya Deep Underground Mine',
    date: '2026-09-11',
    targetTonnage: 4700,
    actualTonnage: 4520,
    variance: -3.8,
    equipmentAvailabilityPercent: 88.0,
    operationalNotes: 'Continuous miner operating steadily in panel 6.',
    anomalyDetected: false
  }
];

export const SEED_CONTRACTORS: Contractor[] = [
  {
    id: 'cont_001',
    code: 'CNT-ECL-042',
    companyName: 'Apex Earthmovers & Heavy Haulage Pvt Ltd',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    contractType: 'Overburden Removal',
    startDate: '2024-04-01',
    endDate: '2027-03-31',
    status: 'Review Required',
    workforceCount: 340,
    complianceScore: 61,
    safetyRating: 'C',
    expiringDocsCount: 2,
    documents: [
      { title: 'Contract Labour R&A License Form VI', expiryDate: '2026-09-28', isExpired: false },
      { title: 'Workmen Compensation & ESIC Policy', expiryDate: '2026-08-31', isExpired: true },
      { title: 'Heavy Vehicle Fitness Certificates (32 Units)', expiryDate: '2026-11-15', isExpired: false }
    ]
  },
  {
    id: 'cont_002',
    code: 'CNT-BCCL-019',
    companyName: 'Koyla Logistics & Tipper Consortium',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    contractType: 'Coal Transportation',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    status: 'Active',
    workforceCount: 185,
    complianceScore: 78,
    safetyRating: 'B',
    expiringDocsCount: 1,
    documents: [
      { title: 'DGMS Tipper Driver Vocational Certificates', expiryDate: '2026-10-02', isExpired: false },
      { title: 'EPFO Challan Remittance Proof', expiryDate: '2026-09-15', isExpired: false }
    ]
  },
  {
    id: 'cont_003',
    code: 'CNT-SECL-088',
    companyName: 'Bharat Heavy Earthmoving Engineering',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    contractType: 'Machinery Maintenance',
    startDate: '2023-10-01',
    endDate: '2026-09-30',
    status: 'Active',
    workforceCount: 95,
    complianceScore: 92,
    safetyRating: 'A',
    expiringDocsCount: 1,
    documents: [
      { title: 'OEM Shovel Maintenance Authorization', expiryDate: '2026-09-30', isExpired: false },
      { title: 'Technician Safety Passports (95 Crew)', expiryDate: '2027-04-10', isExpired: false }
    ]
  },
  {
    id: 'cont_004',
    code: 'CNT-MCL-031',
    companyName: 'Utkal Drilling & Blasting Services',
    mineId: 'mine_shakti',
    mineName: 'Shakti Open Cast Mine',
    contractType: 'Explosives Handling',
    startDate: '2024-06-01',
    endDate: '2027-05-31',
    status: 'Review Required',
    workforceCount: 64,
    complianceScore: 69,
    safetyRating: 'B',
    expiringDocsCount: 2,
    documents: [
      { title: 'PESO Shot Firer Valid Blaster Badges', expiryDate: '2026-09-20', isExpired: false },
      { title: 'Explosive Van Road Permits (PESO Form E)', expiryDate: '2026-08-25', isExpired: true }
    ]
  }
];

export const SEED_ALERTS: AlertItem[] = [
  {
    id: 'alt_001',
    type: 'Critical Violation',
    priority: 'Critical',
    title: 'DGMS Section 22 Notice: Slope Instability on Bench OB-4',
    description: 'Prohibitive notice issued stopping haulage traffic on Ramp 3 due to 18mm tension crack progression.',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    createdAt: '2026-09-08 11:30',
    status: 'Escalated',
    escalationPath: ['Mine Official', 'Director Technical ECL', 'DGMS Regional Inspectorate']
  },
  {
    id: 'alt_002',
    type: 'Overdue Compliance',
    priority: 'Critical',
    title: 'Statutory Telemetry Calibration Past DGMS Deadline',
    description: 'Continuous CH4/CO tele-monitoring sensor calibration certificate overdue since Sept 5 (CMR Reg 153).',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    createdAt: '2026-09-06 09:00',
    status: 'Active',
    escalationPath: ['Ventilation Officer', 'General Manager (Area IX)']
  },
  {
    id: 'alt_003',
    type: 'Environmental Breach',
    priority: 'High',
    title: 'ETP Outfall Total Suspended Solids (TSS) Exceeded',
    description: 'Water discharge TSS recorded at 168 mg/l (Statutory limit: 100 mg/l) into tributary drainage.',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    createdAt: '2026-09-05 16:45',
    status: 'Active'
  },
  {
    id: 'alt_004',
    type: 'Contractor Document Expiry',
    priority: 'High',
    title: 'Apex Haulage Workmen Compensation Insurance Expired',
    description: 'Workmen compensation & ESIC statutory cover expired on Aug 31 for 340 active site personnel.',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    createdAt: '2026-09-01 08:00',
    status: 'Active'
  },
  {
    id: 'alt_005',
    type: 'Production Anomaly',
    priority: 'Medium',
    title: 'Unusual 30% Output Deviation Detected',
    description: 'Daily coal extraction fell from 14,000 MT target to 9,800 MT due to haulage traffic diversions.',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    createdAt: '2026-09-11 20:00',
    status: 'Acknowledged'
  },
  {
    id: 'alt_006',
    type: 'AI Risk Escalation',
    priority: 'High',
    title: 'AI Engine: Bharat Coal Mine Alpha Elevated to HIGH Risk',
    description: 'Risk score elevated to 78 due to concurrent methane telemetry lag, 4 open violations, and production drops.',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    createdAt: '2026-09-10 14:10',
    status: 'Active'
  }
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_001',
    title: 'Critical DGMS Section 22 Issued',
    message: 'Eastern Valley Open Cast received Section 22(3) notice for OB-4 slope cracks.',
    type: 'alert',
    timestamp: '2026-09-08 11:30',
    read: false,
    linkTarget: 'inspections'
  },
  {
    id: 'notif_002',
    title: 'Corrective Action Overdue',
    message: 'CAPA-2026-001 (Shearer power interlock) is overdue for Bharat Coal Mine Alpha.',
    type: 'warning',
    timestamp: '2026-09-07 09:15',
    read: false,
    linkTarget: 'corrective-actions'
  },
  {
    id: 'notif_003',
    title: 'Statutory Report Submitted',
    message: 'Six-monthly EC compliance booklet submitted for Central Ridge Mine via Parivesh.',
    type: 'success',
    timestamp: '2026-08-25 15:00',
    read: true,
    linkTarget: 'compliance'
  },
  {
    id: 'notif_004',
    title: 'AI Anomaly Detected',
    message: 'Production drop of 30% detected at Eastern Valley Open Cast.',
    type: 'info',
    timestamp: '2026-09-11 20:05',
    read: false,
    linkTarget: 'anomalies'
  }
];

export const SEED_GRIEVANCES: GrievanceItem[] = [
  {
    id: 'grv_001',
    code: 'GRV-2026-081',
    category: 'Safety Equipment / PPE',
    submittedBy: 'Rashtriya Colliery Mazdoor Sangh (RCMS Branch)',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    description: 'Delayed supply of anti-static dust masks and replacement cap-lamp lithium battery units for Night Shift timbering crew.',
    priority: 'High',
    assignedDept: 'Store & Safety Equipment Procurement',
    status: 'In Progress',
    createdAt: '2026-09-01',
    dueDate: '2026-09-15'
  },
  {
    id: 'grv_002',
    code: 'GRV-2026-074',
    category: 'Environmental / Dust',
    submittedBy: 'Gram Panchayat Haripur Periphery Committee',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    description: 'Heavy fugitive dust deposition on agricultural paddies along siding road due to irregular water bowser sprinkling.',
    priority: 'Medium',
    assignedDept: 'Civil & CSR Wing',
    status: 'Under Review',
    createdAt: '2026-09-04',
    dueDate: '2026-09-18'
  },
  {
    id: 'grv_003',
    code: 'GRV-2026-069',
    category: 'Wages & Compensation',
    submittedBy: 'Contract Tipper Drivers Association',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    description: 'Non-remittance of statutory variable dearness allowance (VDA) by contractor Apex Earthmovers for July month.',
    priority: 'High',
    assignedDept: 'Labour Welfare & Personnel',
    status: 'Assigned',
    createdAt: '2026-09-03',
    dueDate: '2026-09-17'
  }
];

export const SEED_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_001',
    title: 'DGMS Approval Letter - Seam XV Telemetry Architecture',
    category: 'Compliance Certificate',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    uploadDate: '2026-08-14',
    expiryDate: '2027-08-13',
    uploadedBy: 'Er. Arvind Mukhopadhyay',
    status: 'Valid',
    fileSize: '2.4 MB',
    extractedMetadata: {
      docType: 'DGMS Statutory Sanction',
      refNo: 'DGMS/EZ/SZ/S-15/2026/8912',
      issuingAuth: 'Directorate General of Mines Safety (Dhanbad)',
      issueDate: '2026-08-10',
      expiryDate: '2027-08-13',
      keyClause: 'CMR 2017 Reg 153 - Approval for Automated Continuous CO & Methane Gas Sensors',
      summary: 'Sanction letter granting conditional approval for tele-monitoring sensors across Districts 2 and 3 seams subject to bi-weekly calibration.'
    }
  },
  {
    id: 'doc_002',
    title: 'Central Mining Research Institute (CIMFR) Slope Stability Report',
    category: 'Inspection Report',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    uploadDate: '2026-07-20',
    expiryDate: '2026-10-20',
    uploadedBy: 'Shri B. K. Chattopadhyay',
    status: 'Expiring Soon',
    fileSize: '4.8 MB',
    extractedMetadata: {
      docType: 'Geotechnical Safety Audit',
      refNo: 'CIMFR/GEO/SLP/2026/0411',
      issuingAuth: 'CSIR - Central Institute of Mining and Fuel Research',
      issueDate: '2026-07-15',
      expiryDate: '2026-10-20',
      keyClause: 'CMR 2017 Reg 106 - Factor of Safety Assessment for Overburden Dumps',
      summary: 'Detailed numerical modelling of north-western highwall advising prompt de-stressing of benches OB-4 and OB-5.'
    }
  },
  {
    id: 'doc_003',
    title: 'SPCB Consent to Operate (Water & Air Pollution Acts)',
    category: 'Environmental Report',
    mineId: 'mine_central',
    mineName: 'Central Ridge Mechanized Mine',
    uploadDate: '2025-11-01',
    expiryDate: '2027-10-31',
    uploadedBy: 'Er. Ramesh C. Verma',
    status: 'Valid',
    fileSize: '1.9 MB',
    extractedMetadata: {
      docType: 'Consent to Operate (CTO)',
      refNo: 'CECB/CTO/AIR-WATER/2025/1190',
      issuingAuth: 'Chhattisgarh Environment Conservation Board (CECB)',
      issueDate: '2025-10-28',
      expiryDate: '2027-10-31',
      keyClause: 'Air (P&CP) Act 1981 Section 21 & Water (P&CP) Act 1974 Section 25',
      summary: 'Consolidated consent authorizing 10.0 MTPA coal mining capacity with 14 continuous air monitoring nodes.'
    }
  }
];

export const SEED_FIELD_REPORTS: FieldReport[] = [
  {
    id: 'fld_001',
    code: 'FLD-2026-0912-001',
    mineId: 'mine_eastern',
    mineName: 'Eastern Valley Open Cast',
    category: 'Slope Stability & Geotechnical',
    observation: 'Inspected tension crack marker peg #12 on OB-4. Crack width widened from 6.8cm to 7.4cm after morning rain. Red flag cordon intact.',
    reporterName: 'Smt. Priya Sundaram',
    reporterId: 'usr_insp_01',
    timestamp: '2026-09-12 09:40',
    geoCoordinates: { lat: 23.6895, lng: 86.9676 },
    isGeoTagged: true,
    isTimeStamped: true,
    status: 'Synced'
  },
  {
    id: 'fld_002',
    code: 'FLD-2026-0912-002',
    mineId: 'mine_alpha',
    mineName: 'Bharat Coal Mine Alpha',
    category: 'Gas & Ventilation Audit',
    observation: 'Conducted spot testing with Drager multi-gas detector at Seam XV face. CH4 at 0.28%, CO at 4 ppm, Air velocity 1.4 m/sec. All within limits.',
    reporterName: 'Er. Arvind Mukhopadhyay',
    reporterId: 'usr_mine_01',
    timestamp: '2026-09-12 11:15',
    geoCoordinates: { lat: 23.7960, lng: 86.4310 },
    isGeoTagged: true,
    isTimeStamped: true,
    status: 'Synced'
  }
];

export const SEED_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud_001',
    timestamp: '2026-09-12 11:15:22',
    user: 'Er. Arvind Mukhopadhyay',
    role: 'Mine Official',
    action: 'SUBMIT_FIELD_REPORT',
    module: 'Field Reporting',
    recordId: 'fld_002',
    details: 'Submitted geo-tagged gas spot test report for Seam XV face.',
    ipAddress: '10.14.22.81'
  },
  {
    id: 'aud_002',
    timestamp: '2026-09-11 16:20:05',
    user: 'Er. S. Routray',
    role: 'Mine Official',
    action: 'RESOLVE_CORRECTIVE_ACTION',
    module: 'Corrective Actions',
    recordId: 'ca_005',
    details: 'Marked CAPA-2026-005 (Explosives Barcode Reconciliation) as Resolved.',
    previousValue: 'In Progress',
    newValue: 'Resolved',
    ipAddress: '10.14.30.12'
  },
  {
    id: 'aud_003',
    timestamp: '2026-09-08 11:45:10',
    user: 'Smt. Priya Sundaram',
    role: 'Inspector',
    action: 'CREATE_INSPECTION_VIOLATION',
    module: 'Inspections',
    recordId: 'insp_002',
    details: 'Logged CMR 2017 Reg 106(1) slope tension violation and issued Section 22 notice for Eastern Valley Open Cast.',
    ipAddress: '10.8.19.45'
  },
  {
    id: 'aud_004',
    timestamp: '2026-09-08 12:00:30',
    user: 'System Automated Workflow',
    role: 'System',
    action: 'ESCALATE_ALERT',
    module: 'Alerts',
    recordId: 'alt_001',
    details: 'Automated escalation of Section 22 slope notice to Director Technical ECL and DGMS portal.',
    ipAddress: '127.0.0.1'
  },
  {
    id: 'aud_005',
    timestamp: '2026-09-06 09:00:00',
    user: 'System Automated Rule Engine',
    role: 'System',
    action: 'TRIGGER_OVERDUE_ALERT',
    module: 'Compliance',
    recordId: 'comp_001',
    details: 'Triggered overdue compliance alert for CMR Reg 153 Methane telemetry calibration.',
    ipAddress: '127.0.0.1'
  }
];
