import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import {
  Printer,
  FileText,
  Building,
  Calendar,
  ShieldCheck,
  AlertTriangle,
  Download,
  CheckCircle2
} from 'lucide-react';

export const ReportsView: React.FC = () => {
  const { metrics, mines, compliance, correctiveActions, inspections, currentUser } = useApp();

  const [selectedMine, setSelectedMine] = useState('all');
  const [reportPeriod, setReportPeriod] = useState('Q1-2026');

  const activeMines = selectedMine === 'all' ? mines : mines.filter(m => m.id === selectedMine);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-5">
      {/* Header controls (hidden when printing) */}
      <div className="print:hidden flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white dark:bg-slate-800/80 p-5 rounded-lg border border-slate-200 dark:border-slate-700/80 shadow-xs">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold px-2 py-0.5 rounded bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300">
              OFFICIAL STATUTORY RECORD
            </span>
            <span className="text-xs text-slate-500">DGMS & Ministry of Coal Format</span>
          </div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-white mt-1">
            Statutory Compliance & Executive Audit Report
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Export formal audit dossiers ready for Board of Directors and Regulatory Cell submission
          </p>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={selectedMine}
            onChange={e => setSelectedMine(e.target.value)}
            className="px-3 py-1.5 text-xs bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-md"
          >
            <option value="all">Consolidated All Mines ({mines.length})</option>
            {mines.map(m => (
              <option key={m.id} value={m.id}>{m.name}</option>
            ))}
          </select>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold rounded bg-blue-700 hover:bg-blue-800 text-white transition-colors shadow-xs"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Official Report</span>
          </button>
        </div>
      </div>

      {/* Printable Report Canvas */}
      <div className="bg-white text-slate-900 p-8 sm:p-12 rounded-lg border border-slate-200 shadow-sm print:border-none print:shadow-none print:p-0 max-w-4xl mx-auto space-y-6">
        {/* Ministry Header */}
        <div className="border-b-2 border-slate-900 pb-4 text-center space-y-1">
          <div className="text-xs font-bold uppercase tracking-widest text-slate-600">
            Government of India • Ministry of Coal
          </div>
          <div className="text-xl font-extrabold uppercase tracking-tight">
            Coal India Limited (CIL) & Directorate General of Mines Safety
          </div>
          <div className="text-sm font-semibold text-blue-900">
            SMARTMINE AUTOMATED STATUTORY GOVERNANCE DOSSIER
          </div>
          <div className="text-[11px] text-slate-500 pt-1 flex justify-between">
            <span>Report Run Date: {new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}</span>
            <span>Generated By: {currentUser.name} ({currentUser.roleTitle})</span>
            <span>Audit Cycle: {reportPeriod}</span>
          </div>
        </div>

        {/* Executive Summary Metrics */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
            1. Executive Compliance & Governance KPIs
          </h2>
          <div className="grid grid-cols-4 gap-3 text-center border border-slate-300 p-3 rounded bg-slate-50 text-xs">
            <div>
              <span className="text-[10px] text-slate-500 uppercase font-bold block">Overall Compliance</span>
              <span className="text-xl font-extrabold text-blue-900">{metrics?.overallComplianceRate || 87.4}%</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 uppercase font-bold block">Monitored Leases</span>
              <span className="text-xl font-extrabold text-slate-800">{activeMines.length} Mines</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 uppercase font-bold block">Overdue Filings</span>
              <span className="text-xl font-extrabold text-rose-700">{metrics?.overdueComplianceCount || 2} Breaches</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 uppercase font-bold block">Open CAPAs</span>
              <span className="text-xl font-extrabold text-amber-700">{metrics?.openCapaCount || 5} Actions</span>
            </div>
          </div>
        </div>

        {/* Colliery-wise Rating Table */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
            2. Operational Colliery Risk & Safety Status
          </h2>
          <table className="w-full text-left text-xs border border-slate-300">
            <thead className="bg-slate-100 border-b border-slate-300 text-slate-700 font-bold uppercase text-[10px]">
              <tr>
                <th className="p-2 border-r border-slate-300">Colliery / Leasehold</th>
                <th className="p-2 border-r border-slate-300">Subsidiary</th>
                <th className="p-2 border-r border-slate-300">Type</th>
                <th className="p-2 border-r border-slate-300">Risk Score</th>
                <th className="p-2 border-r border-slate-300">Compliance Rate</th>
                <th className="p-2">Statutory Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {activeMines.map(m => (
                <tr key={m.id}>
                  <td className="p-2 font-bold border-r border-slate-200">{m.name}</td>
                  <td className="p-2 border-r border-slate-200">{m.subsidiaryName}</td>
                  <td className="p-2 border-r border-slate-200">{m.type}</td>
                  <td className="p-2 font-bold border-r border-slate-200">{m.riskScore}/100</td>
                  <td className="p-2 font-bold border-r border-slate-200">{m.complianceRate}%</td>
                  <td className="p-2 font-semibold">
                    {m.riskLevel === 'Critical' ? (
                      <span className="text-rose-700 font-bold">Section 22 Notice Active</span>
                    ) : (
                      <span className="text-emerald-700">Operational License Normal</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Critical Statutory Items Table */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
            3. Outstanding Statutory Clearances & Orders (DGMS / MoEFCC)
          </h2>
          <table className="w-full text-left text-xs border border-slate-300">
            <thead className="bg-slate-100 border-b border-slate-300 text-slate-700 font-bold uppercase text-[10px]">
              <tr>
                <th className="p-2 border-r border-slate-300">Clause</th>
                <th className="p-2 border-r border-slate-300">Title</th>
                <th className="p-2 border-r border-slate-300">Authority</th>
                <th className="p-2 border-r border-slate-300">Status</th>
                <th className="p-2">Responsible Officer</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {compliance.slice(0, 5).map(c => (
                <tr key={c.id}>
                  <td className="p-2 font-mono font-bold border-r border-slate-200">{c.code}</td>
                  <td className="p-2 border-r border-slate-200">{c.title}</td>
                  <td className="p-2 border-r border-slate-200">{c.regulatoryAuthority}</td>
                  <td className="p-2 font-bold border-r border-slate-200">
                    <span className={c.status === 'Overdue' ? 'text-rose-700' : 'text-slate-800'}>
                      {c.status}
                    </span>
                  </td>
                  <td className="p-2">{c.responsiblePerson}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Signatures & Certification Block */}
        <div className="pt-8 border-t border-slate-300 text-xs flex justify-between">
          <div className="text-center w-48 space-y-8">
            <div className="text-[11px] text-slate-400">Certified by Field Authority</div>
            <div className="border-t border-slate-900 pt-1 font-bold">
              Mine Safety Officer
            </div>
          </div>

          <div className="text-center w-48 space-y-8">
            <div className="text-[11px] text-slate-400">Verified by Technical Wing</div>
            <div className="border-t border-slate-900 pt-1 font-bold">
              Director Technical (CIL)
            </div>
          </div>

          <div className="text-center w-48 space-y-8">
            <div className="text-[11px] text-slate-400">Statutory Regulatory Sign-off</div>
            <div className="border-t border-slate-900 pt-1 font-bold">
              DGMS Zonal Controller
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
